### ISSUE TITLE
this._mouseDownEvent is not defined bug

### ISSUE THREAD

**Issue by jboesch** [furf/jquery-ui-touch-punch#14]
In the new version of jQuery UI, they have a variable called this._mouseDownEvent.  This needs to be placed inside your _mouseDown function definition. Here is what I did to temporarily fix the bug.  After I load in your jquery.ui.touch-punch.js file, I duck punch it to add this variable.  Obviously adding this._mouseDownEvent directly into your _mouseDown function would be the fix.  

var _old_mouseDown = $.ui.mouse.prototype._mouseDown;
$.ui.mouse.prototype._mouseDown = function(event){
    this._mouseDownEvent = event;
    return _old_mouseDown.call(this, event);
}

Thanks for a great lib!

**Comment by furf** [comment]
Does this fix address a specific bug that I could reproduce and test?

**Comment by furf** [comment]
I took a look at various versions of jQuery UI. They all contain _mouseDownEvent. Inside of my punched _mouseDown method, I am calling jQuery UI's original _mouseDown method which sets the _mouseDownEvent property. That seems to be setting the property just fine. AFAIK this does not create any problems.

The specific problem I have found involves jQuery UI versions < 1.8 where mouse methods were extended directly onto the widgets rather than being extended from a ui.mouse widget. I will look into solving this once other bugs have been resolved.

In the meanwhile, if you have any specific examples that you could show me, where my code was buggy, I'd appreciate it. Thanks!
