### ISSUE TITLE
Multiple elements at the same time

### ISSUE THREAD

**Issue by dafoer** [furf/jquery-ui-touch-punch#194]
I was trying to use slider with handle on iPad and I noticed I wasn't able to use two handle same time. Is this possible to do?

Also trying with draggable elements but nah, only other element move. jQuery-draggable-touch (https://github.com/heyman/jquery-draggable-touch) seems to have this multiple element (two finger) implemented but it's lacking there features.

**Comment by dafoer** [comment]
No on else has same problem or possible idea how to solve this?

**Comment by dafoer** [comment]
Really? :( No one had no idea where in code should I look to find salutions for this? I'm not but novice but would be willing to changes myself if I just know where to start :)

**Comment by furf** [comment]
Multiple touch events are currently out of the scope of this project which aims only to fill the gap for jQuery UI. Since jQuery UI does not support simultaneous events, neither does Touch Punch. I have considered this in the past and may consider it again in the future but for now, I will close this issue.
