### ISSUE TITLE
helper is not near to my finger

### ISSUE THREAD

**Issue by adminko-svk** [furf/jquery-ui-touch-punch#240]
Hi,
I have problem here - http://www.adminko.info/touch.htm
When you scroll down to the bottom of the page and then you drag any table rows, the helper is not near to my finger.

Can you please help me?

![touch](https://cloud.githubusercontent.com/assets/11200226/9108434/4fe84040-3c2e-11e5-9131-390740aac26f.png)

**Comment by nobitagit** [comment]
It looks more like a jQuery ui/draggable-related issue rather than a Touch Punch one. Have you looked at something like [this](http://stackoverflow.com/questions/5791886/jquery-draggable-shows-helper-in-wrong-place-when-scrolled-down-page) or [this](http://stackoverflow.com/questions/21344286/jquery-draggable-helper-clone-position-offset-from-cursor-after-scroll)?

**Comment by adminko-svk** [comment]
I think this is ui-touch-punch problem because with non-touch device (using computer mouse) everything works fine.

But I will look at your recommended links.

**Comment by nobitagit** [comment]
Actually I tested your link and here's what i experienced:
- FF on desktop OSX: all ok
- Chrome and Safari on desktop OSX: issue as you reported.

The console logs a warning here, which is:

```
Refused to execute script from 'http://raw.githubusercontent.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by adminko-svk** [comment]
It is definitely a jQuery UI problem .
Nobitagit, thank you for your time and consideration!
