### ISSUE TITLE
Draggable doesn't work on android 4.11 & Chrome 27.0.1453.90

### ISSUE THREAD

**Issue by mssoylu** [furf/jquery-ui-touch-punch#99]
Hi

I want use draggable but it doesn't work on android 4.11 & Chrome 27.0.1453.90

I did try diffrent chrome edition and it's work. 

here is example http://jsbin.com/iceqoy/9/edit

How can I fix this bug ?

**Comment by harabara** [comment]
Once you serve jquery.ui.touch-punch.min.js from another place and not from raw.github.com it should work.

**Comment by mssoylu** [comment]
thank you, it's fixed.

**Comment by mikesir87** [comment]
When opening the site in Chrome and connecting to the remote debugger using ADB, the following console error appears:

Refused to execute script from 'https://raw.github.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

So, looks like the punch js library isn't even loaded on Chrome in Android.  Should work on your own site just fine.

**Comment by mikesir87** [comment]
Looks like a combination of the **X-Content-Type-Options: nosniff** and the **Content-type: text/plain** headers being served by the GitHub server.  The file should be served directly from your own server or from GitHub Pages, rather than from GitHub's raw server.
